### ISSUE TITLE
Track Chunk Processing

### ISSUE THREAD

**Issue by littlen101** [littlen101/midi_go#3]
Create functions to finish dealing with tracks 

possible track modes

0, 1 ,2

we were told to only handle 1

**Comment by JavierMunozFdez** [comment]
length doesn't include preceding bytes or itself
F0 (length)
F1 (length)
ff [4]
ff 01 (length)
ff 02 (length)
ff 03 (length)
ff 04 (length)
ff 05 (length)
ff 06 (length)
ff 07 (length)
ff 7f (length)
ff 20 [2]
ff 2f [1]
ff 51 [4]
ff 54 [6]
ff 58 [5]
ff 59 [3]

Everything else is 3 bytes

**Comment by JavierMunozFdez** [comment]
Only 3 events we care about:
8n kk vv :Channel n, Key kk On
9n kk vv :Channel n, Key kk Off
Bn 7B 00 :all notes off

**Comment by littlen101** [comment]
I was told that we can *ignore* all notes off 
Student asked him and said we don't have to worry about it

**Comment by JavierMunozFdez** [comment]
Oh that's good

**Comment by littlen101** [comment]
In terms of what events we need to do we need the **On** and **Off** handled

Depending on how long this takes we can implement ways of handling them

**Comment by littlen101** [comment]
Actually with the way I wanted to implement the process it might now be that bad

- I was thinking that if we use a stack it would make it pretty easy to handle if we can get the information
like how it was in the example
on note -- >[00 90 3E 40]
we push on notes on to a stack and once we encounter an off note
off note -->  [88 00 80 3E 00]
we pop until we match the note - we put the unmatched into a seperate stack and once we found our match we put them back in order

**Comment by JavierMunozFdez** [comment]
That sounds good.

I'm currently working on getting rid of all the events we don't care about and for note on and note off I'll just call whatever function you think should handle it

**Comment by littlen101** [comment]
> Actually with the way I wanted to implement the process it might now be that bad
> 
> * I was thinking that if we use a stack it would make it pretty easy to handle if we can get the information
>   like how it was in the example
>   on note -- >[00 90 3E 40]
>   we push on notes on to a stack and once we encounter an off note
>   off note -->  [88 00 80 3E 00]
>   we pop until we match the note - we put the unmatched into a seperate stack and once we found our match we put them back in order

We don't have to worry about no matches because a note can't be turned on without being off

The only thing I see a problem occuring is that he added a priority to how they need to be printed when they happen at the same time

**Comment by JavierMunozFdez** [comment]
We could have some something like this
Note:
-Start Time
-End Time
-Pitch
-Track
-Channel
-print = "start time, pitch -> note and octave, end-start, track, channel

List of Notes
Sort by start, pitch, track, channel (all ascending)

**Comment by littlen101** [comment]
> That sounds good.
> 
> I'm currently working on getting rid of all the events we don't care about and for note on and note off I'll just call whatever function you think should handle it

Going forward think we just need to establish which version we are working with because I don't want to write function that will work in mine but not yours. Unless we want to just translate later

**Comment by JavierMunozFdez** [comment]
As we go through events we add them to the list and insert correctly.

> Going forward think we just need to establish which version we are working with because I don't want to write function that will work in mine but not yours. Unless we want to just translate later

I think we should work with my version

**Comment by littlen101** [comment]
> We could have some something like this
> Note:
> -Start Time
> -End Time
> -Pitch
> -Track
> -Channel
> -print = "start time, pitch -> note and octave, end-start, track, channel
> 
> List of Notes
> Sort by start, pitch, track, channel (all ascending)

Yeah was thinking , just gotta find how to make comparable objects now
